name: sliding_puzzle
description: "拼图滑块"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.2
  json_serializable: ^6.9.4
  json_annotation: ^4.9.0
  build_runner: ^2.4.15
  flutter_soloud: ^3.1.1
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true
  assets:
    - assets/sounds/music/mixkit-goin-back-to-alabama-830.mp3
    - assets/sounds/tap/mixkit-modern-click-box-check-1120.wav
    - assets/images/star.png
    - assets/images/bg.png
    - assets/images/bg2.png
    - assets/images/bg3.png
    - assets/images/star_d.png
    - assets/images/star_s.png
    - assets/images/start_button_image.png
    - assets/images/start_button_image_g.png
    - assets/images/start_button_image_s.png
    - assets/images/chest_l.png
    - assets/images/title.png
    - assets/images/level/1-1.png
    - assets/images/level/1-1/0.png
    - assets/images/level/1-1/1.png
    - assets/images/level/1-1/2.png
    - assets/images/level/1-1/3.png
    - assets/images/level/1-1/4.png
    - assets/images/level/1-1/5.png
    - assets/images/level/1-1/6.png
    - assets/images/level/1-1/7.png
    - assets/images/level/1-1/8.png
    - assets/images/level/1-2.png
    - assets/images/level/1-2/0.png
    - assets/images/level/1-2/1.png
    - assets/images/level/1-2/2.png
    - assets/images/level/1-2/3.png
    - assets/images/level/1-2/4.png
    - assets/images/level/1-2/5.png
    - assets/images/level/1-2/6.png
    - assets/images/level/1-2/7.png
    - assets/images/level/1-2/8.png
    - assets/images/level/1-3.png
    - assets/images/level/1-3/0.png
    - assets/images/level/1-3/1.png
    - assets/images/level/1-3/2.png
    - assets/images/level/1-3/3.png
    - assets/images/level/1-3/4.png
    - assets/images/level/1-3/5.png
    - assets/images/level/1-3/6.png
    - assets/images/level/1-3/7.png
    - assets/images/level/1-3/8.png
  uses-material-design: true

