name: sliding_puzzle
description: "拼图滑块"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.2
  json_serializable: ^6.9.4
  json_annotation: ^4.9.0
  build_runner: ^2.4.15
  flutter_soloud: ^3.1.1
  flutter_localizations:
    sdk: flutter
  intl: any
  games_services: ^4.1.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  ios: true # 设置为 true 以生成 iOS 图标
  image_path: "assets/icon/ic_launcher.png"
  remove_alpha_ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true
  assets:
    - assets/sounds/music/countd.mp3
    - assets/sounds/music/success.mp3
    - assets/sounds/music/mixkit-goin-back-to-alabama-830.mp3
    - assets/sounds/tap/mixkit-modern-click-box-check-1120.wav
    - assets/sounds/tap/happy-pop2.mp3
    - assets/sounds/tap/happy-pop-3-185288.mp3
    - assets/sounds/tap/ui-pop-sound-316482.mp3
    - assets/sounds/tap/808-deep-kick-87379.mp3
    - assets/sounds/tap/smooth-completed.mp3
    - assets/sounds/tap/n.mp3
    - assets/icon/ic_launcher.png
    - assets/images/tree1.webp
    - assets/images/bb1.webp
    - assets/images/bb2.webp
    - assets/images/b/b1.png
    - assets/images/game_name.webp
    - assets/images/b/b2.png
    - assets/images/b/b3.png
    - assets/images/b/b4.png
    - assets/images/b/b5.png
    - assets/images/b/b6.png
    - assets/images/b/b7.png
    - assets/images/b/b8.png
    - assets/images/b/b9.png
    - assets/images/bg1.webp
    - assets/images/bg2.webp
    - assets/images/bg3.webp
    - assets/images/star.png
    - assets/images/num3.webp
    - assets/images/num4.webp
    - assets/images/num5.webp
    - assets/images/star_d.png
    - assets/images/star_s.png
    - assets/images/start_button_image.png
    - assets/images/start_button_image_g.png
    - assets/images/start_button_image_s.png
    - assets/images/chest_l.png
    - assets/images/title.png
    - assets/images/level/1.png
    - assets/images/level/1/0.png
    - assets/images/level/1/1.png
    - assets/images/level/1/2.png
    - assets/images/level/1/3.png
    - assets/images/level/1/4.png
    - assets/images/level/1/5.png
    - assets/images/level/1/6.png
    - assets/images/level/1/7.png
    - assets/images/level/1/8.png
    - assets/images/level/2.png
    - assets/images/level/2/0.png
    - assets/images/level/2/1.png
    - assets/images/level/2/2.png
    - assets/images/level/2/3.png
    - assets/images/level/2/4.png
    - assets/images/level/2/5.png
    - assets/images/level/2/6.png
    - assets/images/level/2/7.png
    - assets/images/level/2/8.png
    - assets/images/level/3.png
    - assets/images/level/3/0.png
    - assets/images/level/3/1.png
    - assets/images/level/3/2.png
    - assets/images/level/3/3.png
    - assets/images/level/3/4.png
    - assets/images/level/3/5.png
    - assets/images/level/3/6.png
    - assets/images/level/3/7.png
    - assets/images/level/3/8.png
    - assets/images/level/4.png
    - assets/images/level/4/0.png
    - assets/images/level/4/1.png
    - assets/images/level/4/2.png
    - assets/images/level/4/3.png
    - assets/images/level/4/4.png
    - assets/images/level/4/5.png
    - assets/images/level/4/6.png
    - assets/images/level/4/7.png
    - assets/images/level/4/8.png
    - assets/images/level/5.png
    - assets/images/level/5/0.png
    - assets/images/level/5/1.png
    - assets/images/level/5/2.png
    - assets/images/level/5/3.png
    - assets/images/level/5/4.png
    - assets/images/level/5/5.png
    - assets/images/level/5/6.png
    - assets/images/level/5/7.png
    - assets/images/level/5/8.png
    - assets/images/level/6.png
    - assets/images/level/6/0.png
    - assets/images/level/6/1.png
    - assets/images/level/6/2.png
    - assets/images/level/6/3.png
    - assets/images/level/6/4.png
    - assets/images/level/6/5.png
    - assets/images/level/6/6.png
    - assets/images/level/6/7.png
    - assets/images/level/6/8.png
    - assets/images/level/7.png
    - assets/images/level/7/0.png
    - assets/images/level/7/1.png
    - assets/images/level/7/2.png
    - assets/images/level/7/3.png
    - assets/images/level/7/4.png
    - assets/images/level/7/5.png
    - assets/images/level/7/6.png
    - assets/images/level/7/7.png
    - assets/images/level/7/8.png
    - assets/images/level/7/9.png
    - assets/images/level/7/10.png
    - assets/images/level/7/11.png
    - assets/images/level/7/12.png
    - assets/images/level/7/13.png
    - assets/images/level/7/14.png
    - assets/images/level/7/15.png
    - assets/images/level/8.png
    - assets/images/level/8/0.png
    - assets/images/level/8/1.png
    - assets/images/level/8/2.png
    - assets/images/level/8/3.png
    - assets/images/level/8/4.png
    - assets/images/level/8/5.png
    - assets/images/level/8/6.png
    - assets/images/level/8/7.png
    - assets/images/level/8/8.png
    - assets/images/level/8/9.png
    - assets/images/level/8/10.png
    - assets/images/level/8/11.png
    - assets/images/level/8/12.png
    - assets/images/level/8/13.png
    - assets/images/level/8/14.png
    - assets/images/level/8/15.png
    - assets/images/level/9.png
    - assets/images/level/9/0.png
    - assets/images/level/9/1.png
    - assets/images/level/9/2.png
    - assets/images/level/9/3.png
    - assets/images/level/9/4.png
    - assets/images/level/9/5.png
    - assets/images/level/9/6.png
    - assets/images/level/9/7.png
    - assets/images/level/9/8.png
    - assets/images/level/9/9.png
    - assets/images/level/9/10.png
    - assets/images/level/9/11.png
    - assets/images/level/9/12.png
    - assets/images/level/9/13.png
    - assets/images/level/9/14.png
    - assets/images/level/9/15.png
    - assets/images/level/10.png
    - assets/images/level/10/0.png
    - assets/images/level/10/1.png
    - assets/images/level/10/2.png
    - assets/images/level/10/3.png
    - assets/images/level/10/4.png
    - assets/images/level/10/5.png
    - assets/images/level/10/6.png
    - assets/images/level/10/7.png
    - assets/images/level/10/8.png
    - assets/images/level/10/9.png
    - assets/images/level/10/10.png
    - assets/images/level/10/11.png
    - assets/images/level/10/12.png
    - assets/images/level/10/13.png
    - assets/images/level/10/14.png
    - assets/images/level/10/15.png
    - assets/images/level/10/16.png
    - assets/images/level/10/17.png
    - assets/images/level/10/18.png
    - assets/images/level/10/19.png
    - assets/images/level/10/20.png
    - assets/images/level/10/21.png
    - assets/images/level/10/22.png
    - assets/images/level/10/23.png
    - assets/images/level/10/24.png
    - assets/images/level/11.png
    - assets/images/level/11/0.png
    - assets/images/level/11/1.png
    - assets/images/level/11/2.png
    - assets/images/level/11/3.png
    - assets/images/level/11/4.png
    - assets/images/level/11/5.png
    - assets/images/level/11/6.png
    - assets/images/level/11/7.png
    - assets/images/level/11/8.png
    - assets/images/level/11/9.png
    - assets/images/level/11/10.png
    - assets/images/level/11/11.png
    - assets/images/level/11/12.png
    - assets/images/level/11/13.png
    - assets/images/level/11/14.png
    - assets/images/level/11/15.png
    - assets/images/level/11/16.png
    - assets/images/level/11/17.png
    - assets/images/level/11/18.png
    - assets/images/level/11/19.png
    - assets/images/level/11/20.png
    - assets/images/level/11/21.png
    - assets/images/level/11/22.png
    - assets/images/level/11/23.png
    - assets/images/level/11/24.png

  uses-material-design: true

